//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplanMVC.EntityFrameworkModelClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentMaster
    {
        public int DeptId { get; set; }
        public string DeptName { get; set; }
        public string DeptDescription { get; set; }
        public string DeptHead { get; set; }
        public Nullable<int> DeptState { get; set; }
        public Nullable<decimal> DeptHeadSalary { get; set; }
    }
}
